### ISSUE TITLE
Installation failing on Ubuntu 22.04

### ISSUE THREAD

**Issue by jamiemtdwyer** [halfhelix/Kit#32]
Replicable on latest release as well as `kit@0.0.1-beta.30`

```
npm ERR! code 1
npm ERR! path /home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /home/jamied/.nvm/versions/node/v18.16.0/bin/node /home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/home/jamied/.nvm/versions/node/v18.16.0/bin/node',
npm ERR! gyp verb cli   '/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.16.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 18.16.0
npm ERR! gyp verb command install [ '18.16.0' ]
npm ERR! gyp verb install input version string "18.16.0"
npm ERR! gyp verb install installing version: 18.16.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 18.16.0
npm ERR! gyp verb build dir attempting to create "build" dir: /home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass/build/config.gypi
npm ERR! (node:119405) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: /home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jamied/.node-gyp/18.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/jamied/.node-gyp/18.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/jamied/.node-gyp/18.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
npm ERR!     params['parallel'], params['root_targets'])
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
npm ERR!     variables, includes, depth, check, True)
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
npm ERR!     includes, True, check)
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
npm ERR!     aux_data, includes, check)
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
npm ERR!     LoadOneBuildFile(include, data, aux_data, None, False, check),
npm ERR!   File "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
npm ERR!     None)
npm ERR!   File "/home/jamied/.node-gyp/18.16.0/include/node/common.gypi", line 1
npm ERR!     e_data_file_flag%': 1
npm ERR!                         ^
npm ERR! SyntaxError: EOL while scanning string literal
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 6.0.12-76060006-generic
npm ERR! gyp ERR! command "/home/jamied/.nvm/versions/node/v18.16.0/bin/node" "/home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/jamied/.nvm/versions/node/v18.16.0/lib/node_modules/@halfhelix/kit/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jamied/.npm/_logs/2023-05-01T21_44_33_435Z-debug-0.log
```

OS: Pop!_OS 22.04 LTS (Ubuntu 22.04 LTS)
Kernel version: 6.0.12-76060006-generic
Python2 version: 2.7.18 (final release)
Node version: v18.16.0 (LTS)

**Comment by sahilmobikasa** [comment]
@jamiemtdwyer Any update for this issue?
